name:                tophat
version:             1.0.6.0
license:             GPL-3
author:              "James Cranch"
maintainer:          "j.d.cranch@sheffield.ac.uk"
copyright:           "2020-21 James Cranch"
homepage:            "https://github.com/jcranch/tophat"

extra-source-files:
- README.md
- ChangeLog.md
- app-test-bin/*.tpt.txt

synopsis:            Template-to-Haskell preprocessor, and templating language
category:            Web
description:         Please see README.md

dependencies:
- base               >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - profunctors      >= 5.2.2 && < 6
  - text             >= 1.2.3 && < 2.1
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

executables:
  tophat:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - filepath           >= 1.4.2 && < 1.6
    - tophat
    - text

tests:

  src-test:
    main:                Spec.hs
    source-dirs:
    - src-test
    - src
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tophat
    - profunctors
    - hspec              >= 2.5.5 && < 3
    - text

  app-test-src:
    main:                Spec.hs
    source-dirs:
    - app-test-src
    - app
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tophat
    - hspec
    - text

  app-test-bin:
    main:                Spec.hs
    source-dirs:         app-test-bin
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    build-tools:
    - tophat:tophat
    dependencies:
    - tophat
    - text
    - hspec
